//this variable will hold a random number generated by the random() function
long randomNumber;
String textout;

//Set up - this is where you get things "set-up". It will only run once
void setup() {
  
  //setup serial communications through the USB
  Serial.begin(115200);

  //Let's make it more random
  randomSeed(42);   
      
}//close setup

void loop() {
  
  //generate a random number
  randomNumber = random(0,100);
  
  //display the random number on the serial monitor
  if(randomNumber < 10){
    textout = "00" + String(randomNumber);
  }
  else if(randomNumber < 100 && randomNumber > 9){
    textout = "0" + String(randomNumber);
  }
  else{
    textout = String(randomNumber);
  }
  
  Serial.print(textout);
  
}
